name: Release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "auto"
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
          - prerelease
          - prepatch
          - preminor
          - premajor
  pull_request:
    types: [closed]

jobs:
  release:
    if: >-
      ${{
        (
          startsWith(github.event.inputs.semver, 'pre') ||
          github.ref == format(
            'refs/heads/{0}',
            github.event.repository.default_branch
          )
        ) &&
        (
          github.event_name != 'pull_request' ||
          github.event.pull_request.user.login == 'optic-release-automation[bot]'
        )
      }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - uses: nearform-actions/optic-release-automation-action@9e3518763346efacba15d729d0faaa4cbd8fdd52 # v4.12.3
        with:
          commit-message: "Release {version}"
          sync-semver-tags: false
          access: "public"
          # This prefix is added before the prerelease number, e.g. `v3.0.0-pre.0`
          prerelease-prefix: "pre"
          semver: ${{ github.event.inputs.semver }}
          # Prereleases are published under the `next` npm dist-tag
          npm-tag: ${{ startsWith(github.event.inputs.semver, 'pre') && 'next' || 'latest' }}
          # Don't notify linked issues
          notify-linked-issues: false
          publish-mode: oidc
          build-command: |
            npm ci
